version: "3.8"

services:
  feed-generator:
    build: .
    container_name: bsky-feed-generator
    restart: unless-stopped
    volumes:
      - ./data:/app/data
    environment:
      - NODE_ENV=production
    env_file:
      - .env
    networks:
      - caddy_network

  caddy:
    image: caddy:2
    container_name: caddy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - caddy_network

networks:
  caddy_network:
    driver: bridge

volumes:
  caddy_data:
  caddy_config:
